/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2021 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#include "../../inc/MarlinConfigPre.h"

#if HAS_MARLINUI_U8GLIB

#include "ui_theme.h"

// Stock reuses Marlin's own existing bitmaps unchanged -- no generated art.
// _Bootscreen.h is self-contained (just the bitmap + a couple of #defines).
// The status logo/hotend/bed/fan bitmaps are pulled in via dogm_Statusscreen.h
// rather than including status/hotend.h etc. directly, because those files
// depend on preprocessor context (STATUS_HOTEND_BITMAPS, STATUS_FAN_FRAMES,
// STATUS_ALT_*_BITMAP, ...) that dogm_Statusscreen.h is what actually sets up
// correctly, in the right order, for this build's config -- reusing it here
// guarantees this file sees exactly the same Stock bitmaps status_screen_DOGM.cpp
// does, instead of re-deriving that setup by hand and risking it drifting out
// of sync.
// dogm_Statusscreen.h must come first: it pulls in the full HAL/Arduino
// include chain (binary.h) that defines the `Bxxxxxxxx` byte-literal macros
// these bitmap headers are written with -- including _Bootscreen.h before
// that chain is established leaves those macros undefined.
#include "dogm_Statusscreen.h"
#include "../../../_Bootscreen.h"

// Generated by tools/lcd_theme_gen/lcd_theme_gen.py -- see
// tools/lcd_theme_gen/examples/ender3max_reskin.yaml,
// tools/lcd_theme_gen/examples/ender3max_layout2.yaml, and
// tools/lcd_theme_gen/examples/ender3max_stock_inverted.yaml.
// Re-run the generator after changing theme art; don't hand-edit these.
#include "theme_assets/ui_theme_reskin.h"
#include "theme_assets/ui_theme_layout2.h"
#include "theme_assets/ui_theme_stock_inverted.h"

const char* const ui_theme_names[UI_THEME_INDEX_COUNT] = {
  "Stock",         "Stock (Dark)",
  "Reskin",        "Reskin (Dark)",
  "Reskin+Layout", "Reskin+Layout (Dark)",
};

// Index order for every table below matches UIThemeID x { normal, inverted }:
//   0 UI_THEME_STOCK   normal      1 UI_THEME_STOCK   inverted
//   2 UI_THEME_RESKIN  normal      3 UI_THEME_RESKIN  inverted
//   4 UI_THEME_LAYOUT2 normal      5 UI_THEME_LAYOUT2 inverted

const u8g_pgm_uint8_t* const ui_theme_bootscreen_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  custom_start_bmp,             theme_stock_bootscreen_bmp_inv,
  theme_reskin_bootscreen_bmp,  theme_reskin_bootscreen_bmp_inv,
  theme_layout2_bootscreen_bmp, theme_layout2_bootscreen_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_status_logo_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_logo_bmp,                theme_stock_status_logo_bmp_inv,
  theme_reskin_status_logo_bmp,   theme_reskin_status_logo_bmp_inv,
  theme_layout2_status_logo_bmp,  theme_layout2_status_logo_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_hotend_off_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_hotend_a_bmp,            theme_stock_hotend_off_bmp_inv,
  theme_reskin_hotend_off_bmp,    theme_reskin_hotend_off_bmp_inv,
  theme_layout2_hotend_off_bmp,   theme_layout2_hotend_off_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_hotend_on_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_hotend_b_bmp,            theme_stock_hotend_on_bmp_inv,
  theme_reskin_hotend_on_bmp,     theme_reskin_hotend_on_bmp_inv,
  theme_layout2_hotend_on_bmp,    theme_layout2_hotend_on_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_bed_off_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_bed_bmp,                 theme_stock_bed_off_bmp_inv,
  theme_reskin_bed_off_bmp,       theme_reskin_bed_off_bmp_inv,
  theme_layout2_bed_off_bmp,      theme_layout2_bed_off_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_bed_on_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_bed_on_bmp,              theme_stock_bed_on_bmp_inv,
  theme_reskin_bed_on_bmp,        theme_reskin_bed_on_bmp_inv,
  theme_layout2_bed_on_bmp,       theme_layout2_bed_on_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_fan0_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_fan0_bmp,                theme_stock_fan0_bmp_inv,
  theme_reskin_fan0_bmp,          theme_reskin_fan0_bmp_inv,
  theme_layout2_fan0_bmp,         theme_layout2_fan0_bmp_inv,
};

const u8g_pgm_uint8_t* const ui_theme_fan1_bmp[UI_THEME_INDEX_COUNT] PROGMEM = {
  status_fan1_bmp,                theme_stock_fan1_bmp_inv,
  theme_reskin_fan1_bmp,          theme_reskin_fan1_bmp_inv,
  theme_layout2_fan1_bmp,         theme_layout2_fan1_bmp_inv,
};

#endif // HAS_MARLINUI_U8GLIB
